--- net/core/Makefile
+++ net/core/Makefile
@@ -21,3 +21,4 @@
 obj-$(CONFIG_NET_DROP_MONITOR) += drop_monitor.o
 obj-$(CONFIG_NETWORK_PHY_TIMESTAMPING) += timestamping.o
 obj-$(CONFIG_NETPRIO_CGROUP) += netprio_cgroup.o
+obj-$(CONFIG_SOCKEV_NLMCAST) += sockev_nlmcast.o
